export default [
    { id: 1, name: "Accident", link: "/Accident", checked: false },
    { id: 2, name: "Automotive", link: "/Automotive", checked: false },
    { id: 3, name: "Bail Bonds", link: "/Bail-Bonds", checked: false },
    { id: 4, name: "Banking", link: "/Banking", checked: false },
    { id: 5, name: "Beverages/Spirits", link: "/Beverages/Spirits", checked: false },
    { id: 6, name: "Cable TV", link: "/Cable-TV", checked: false },
    { id: 7, name: "Call-To-Action", link: "/Call-To-Action", checked: false },
    { id: 8, name: "Chiropractors", link: "/Chiropractors", checked: false },
    { id: 9, name: "Cities/States/Countries", link: "/Cities/States/Countries", checked: false },
    { id: 10, name: "Computer", link: "/Computer", checked: false },
    { id: 11, name: "Construction", link: "/Construction", checked: false },
    { id: 12, name: "Cosmetic", link: "/Cosmetic", checked: false },
    { id: 13, name: "Credit Repair", link: "/Credit-Repair", checked: false },
    { id: 14, name: "Criminal Law", link: "/Criminal-Law", checked: false },
    { id: 15, name: "DUI/DWI", link: "/DUI/DWI", checked: false },
    { id: 16, name: "Debt Consolidation", link: "/Debt-Consolidation", checked: false },
    { id: 17, name: "Dental", link: "/Dental", checked: false },
    { id: 18, name: "Doctors", link: "/Doctors", checked: false },
    { id: 19, name: "Eco/Green", link: "/Eco/Green", checked: false },
    { id: 20, name: "Education/College", link: "/Education/College", checked: false },
    { id: 21, name: "Entertainment", link: "/Entertainment", checked: false },
    { id: 22, name: "Family Law", link: "/Family-Law", checked: false },
    { id: 23, name: "Financial Services", link: "/Financial-Services", checked: false },
    { id: 24, name: "First Names", link: "/First-Names", checked: false },
    { id: 25, name: "Foreign Language", link: "/Foreign-Language", checked: false },
    { id: 27, name: "Furniture", link: "/Furniture", checked: false },
    { id: 28, name: "Health Care", link: "/Health-Care", checked: false },
    { id: 29, name: "Heat/Oil", link: "/Heat/Oil", checked: false },
    { id: 30, name: "Home Help", link: "/Home-Help", checked: false },
    { id: 31, name: "Home Improvement", link: "/Home-Improvement", checked: false },
    { id: 32, name: "Home Medical Equipment", link: "/Home-Medical-Equipment", checked: false },
    { id: 33, name: "Homecare", link: "/Homecare", checked: false },
    { id: 34, name: "Hospice Care", link: "/Hospice-Care", checked: false },
    { id: 35, name: "Hospitals/Medical", link: "/Hospitals/Medical", checked: false },
    { id: 36, name: "Interior Design", link: "/Interior-Design", checked: false },
    { id: 37, name: "Investment", link: "/Investment", checked: false },
    { id: 38, name: "Jobs/Careers", link: "/Jobs/Careers", checked: false },
    { id: 39, name: "Last Names", link: "/Last-Names", checked: false },
    { id: 40, name: "Legal", link: "/Legal", checked: false },
    { id: 41, name: "Legal/General", link: "/Legal/General", checked: false },
    { id: 42, name: "Legal/Immigration", link: "/Legal/Immigration", checked: false },
    { id: 43, name: "Legal/Personal Injury", link: "/Legal/Personal Injury", checked: false },
    { id: 44, name: "Maritime Law", link: "/Maritime-Law", checked: false },
    { id: 45, name: "Martial Arts", link: "/Martial-Arts", checked: false },
    { id: 46, name: "Mass Tort", link: "/Mass-Tort", checked: false },
    { id: 47, name: "Media & Communications", link: "/Media-Communications", checked: false },
    { id: 48, name: "Medical", link: "/Medical", checked: false },
    { id: 49, name: "Mortgage/Refinance", link: "/Mortgage/Refinance", checked: false },
    { id: 50, name: "Motorcycles", link: "/Motorcycles", checked: false },
    { id: 51, name: "Moving/Trucking/Storage", link: "/Moving/Trucking/Storage", checked: false },
    { id: 52, name: "Music", link: "/Music", checked: false },
    { id: 53, name: "Pet Care", link: "/Pet-Care", checked: false },
    { id: 54, name: "Pizza", link: "/Pizza", checked: false },
    { id: 55, name: "Podiatry", link: "/Podiatry", checked: false },
    { id: 56, name: "Politics/Elections", link: "/Politics/Elections", checked: false },
    { id: 57, name: "Printing", link: "/Printing", checked: false },
    { id: 58, name: "Radio", link: "/Radio", checked: false },
    { id: 59, name: "Real Estate", link: "/Real-Estate", checked: false },
    { id: 60, name: "Recreation", link: "/Recreation", checked: false },
    { id: 61, name: "Religious/Faith", link: "/Religious/Faith", checked: false },
    { id: 62, name: "Repair Services", link: "/Repair-Services", checked: false },
    { id: 63, name: "Restaurants/Food", link: "/Restaurants/Food", checked: false },
    { id: 64, name: "Retail", link: "/Retail", checked: false },
    { id: 65, name: "Retirement Services", link: "/Retirement-Services", checked: false },
    { id: 66, name: "Self Help", link: "/Self-Help", checked: false },
    { id: 67, name: "Services", link: "/Services", checked: false },
    { id: 68, name: "Shopping/Gifts", link: "/Shopping/Gifts", checked: false },
    { id: 69, name: "Social Security/Disability", link: "/Social-Security/Disability", checked: false },
    { id: 70, name: "Spa/Fitness", link: "/Spa/Fitness", checked: false },
    { id: 71, name: "Spanish Legal", link: "/Spanish-Legal", checked: false },
    { id: 72, name: "Sports Related", link: "/Sports-Related", checked: false },
    { id: 73, name: "Switch", link: "/Switch", checked: false },
    { id: 74, name: "Tanning", link: "/Tanning", checked: false },
    { id: 75, name: "Taxation", link: "/Taxation", checked: false },
    { id: 76, name: "Transportation", link: "/Transportation", checked: false },
    { id: 77, name: "VOIP", link: "/VOIP", checked: false },
    { id: 78, name: "Vacation & Resorts", link: "/Vacation-Resorts", checked: false },
    { id: 79, name: "Water/H2O", link: "/Water/H2O", checked: false },
    { id: 80, name: "Wireless", link: "/Wireless", checked: false },


]