
/**
 * login constants
 */
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST"
export const SIGN_IN_REQUEST_SUCCESS = "SIGN_IN_REQUEST_SUCCESS"
export const SIGN_IN_REQUEST_ERROR = "SIGN_IN_REQUEST_ERROR"

/**
 * logout constants
 */
export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST"
export const SIGN_OUT_REQUEST_SUCCESS = "SIGN_OUT_REQUEST_SUCCESS"
export const SIGN_OUT_REQUEST_ERROR = "SIGN_OUT_REQUEST_ERROR"

/**
 * sign up constants
 */
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS"
export const SIGN_UP_REQUEST_ERROR = "SIGN_UP_REQUEST_ERROR"

/**
 * Search constants
 */
export const SEARCH_RESULT_REQUEST = "SEARCH_RESULT_REQUEST"
export const SEARCH_RESULT_REQUEST_SUCCESS = "SEARCH_RESULT_REQUEST_SUCCESS"
export const SEARCH_RESULT_REQUEST_ERROR = "SEARCH_RESULT_REQUEST_ERROR"
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS"


/**
 * toast constants
 */

export const TOAST_STATUS = "TOAST_STATUS"

/**
 * Form constants
 */
export const ON_FORM_CHANGE = "ON_FORM_CHANGE"
export const CLEAR_FORM = "CLEAR_FORM"
export const IS_REQUIRED = "IS_REQUIRED"
export const FORM_MESSAGE = "FORM_MESSAGE"
export const IS_VALID = "IS_VALID"
export const SET_FORM_VALUES = "SET_FORM_VALUES"

/**
 * Token constants
 */
export const TOKEN = "TOKEN"


//** Favorite Number Actions */
export const ADD_FAVORITE_NUMBER_BEGIN = "ADD_FAVORITE_NUMBER_BEGIN"
export const ADD_FAVORITE_NUMBER_SUCCESS = "ADD_FAVORITE_NUMBER_SUCCESS"
export const ADD_FAVORITE_NUMBER_ERROR = "ADD_FAVORITE_NUMBER_ERROR"



//** Feature Numbers **/
export const GET_FEATURED_NUMBERS_BEGIN = "GET_FEATURED_NUMBERS_BEGIN"
export const GET_FEATURED_NUMBERS_SUCCESS = "GET_FEATURED_NUMBERS_SUCCESS"
export const GET_FEATURED_NUMBERS_ERROR = "GET_FEATURED_NUMBERS_ERROR"
export const UPDATE_FEATURED_NUMBERS = "UPDATE_FEATURED_NUMBERS"


//** CART ACTIONS **/
export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST"
export const GET_CART_ITEMS_REQUEST_SUCCESS = "GET_CART_ITEMS_REQUEST_SUCCESS"
export const GET_CART_ITEMS_REQUEST_ERROR = "GET_CART_ITEMS_REQUEST_ERROR"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_REQUEST_SUCCESS = "ADD_TO_CART_REQUEST_SUCCESS"
export const ADD_TO_CART_REQUEST_ERROR = "ADD_TO_CART_REQUEST_ERROR"

export const DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST"
export const DELETE_FROM_CART_REQUEST_SUCCESS = "DELETE_FROM_CART_REQUEST_SUCCESS"
export const DELETE_FROM_CART_REQUEST_ERROR = "DELETE_FROM_CART_REQUEST_ERROR"

/**
 * Loader constants
 */
export const SHOW_LOADER = "SHOW_LOADER"
export const HIDE_LOADER = "HIDE_LOADER"

/**
 * User info constants
 */
export const ADD_USER_INFO_REQUEST = "ADD_USER_INFO_REQUEST"
export const ADD_USER_INFO_REQUEST_SUCCESS = "ADD_USER_INFO_REQUEST_SUCCESS"
export const ADD_USER_INFO_REQUEST_ERROR = "ADD_USER_INFO_REQUEST_ERROR"

export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST"
export const GET_USER_INFO_REQUEST_SUCCESS = "GET_USER_INFO_REQUEST_SUCCESS"
export const GET_USER_INFO_REQUEST_ERROR = "GET_USER_INFO_REQUEST_ERROR"

export const UPDATE_USER_INFO_REQUEST = "UPDATE_USER_INFO_REQUEST"
export const UPDATE_USER_INFO_REQUEST_SUCCESS = "UPDATE_USER_INFO_REQUEST_SUCCESS"
export const UPDATE_USER_INFO_REQUEST_ERROR = "UPDATE_USER_INFO_REQUEST_ERROR"


/**
 * Reset password
 */

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS"
export const RESET_PASSWORD_REQUEST_ERROR = "RESET_PASSWORD_REQUEST_ERROR"


/**
 * Check out
 */

export const CHECK_OUT_REQUEST = "CHECK_OUT_REQUEST"
export const CHECK_OUT_REQUEST_SUCCESS = "CHECK_OUT_REQUEST_SUCCESS"
export const CHECK_OUT_REQUEST_ERROR = "CHECK_OUT_REQUEST_ERROR"

/**
 * Get favorites
 */

export const GET_FAVORITE_NUMBER_BEGIN = "GET_FAVORITE_NUMBER_BEGIN"
export const GET_FAVORITE_NUMBER_SUCCESS = "GET_FAVORITE_NUMBER_SUCCESS"
export const GET_FAVORITE_NUMBER_ERROR = "GET_FAVORITE_NUMBER_ERROR"

/**
 * List
 */

export const CATEGORY_LIST_BEGIN = "CATEGORY_LIST_BEGIN"
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS"
export const CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR"
export const CATEGORY_LIST_UPDATE = "CATEGORY_LIST_UPDATE"